/**
 * User model(Entity)
 * fields:email, password, role, verificationToken, isVerified, verified, passwordToken,  passwordTokenExpirationDate
 */

const Key = require("./KeyModel");
const mongoose = require("mongoose");
const validator = require("validator");
const bcrypt = require("bcryptjs");
const UserSchema = new mongoose.Schema(
  {
    email: {
      type: String,
      unique: true,
      required: [true, "Please enter your email address"],
      maxlength: 100,
      validate: {
        validator: validator.isEmail,
        message: "Please provide a valid email address",
      },
    },

    password: {
      type: String,
      required: [true, "Please enter your password"],
      minlength: 6,
      select: false,
    },
    role: {
      type: String,
      enum: ["admin", "school"],
      default: "school",
    },

    verificationToken: String,
    isVerified: {
      type: Boolean,
      default: false,
    },
    verified: Date,
    passwordToken: {
      type: String,
    },
    passwordTokenExpirationDate: {
      type: Date,
    },
  },
  { timestamps: true }
);

UserSchema.index({ email: 1 }, { unique: true });

UserSchema.pre(["remove", "deleteOne"], async function (next) {
  /**
   * Ensures that when a user is deleted, all the keys generated by that user gets deleted
   */
  try {
    await Key.deleteMany({ user: this._id });
    next();
  } catch (error) {
    next(error);
  }
});
UserSchema.pre("save", async function () {
  /**
   * Checks if password is modified, if not returns
   */
  if (!this.isModified("password")) return;
  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
});

UserSchema.methods.comparePassword = async function (userPassword) {
  /**
   * Compares use's password with the password in the database
   */
  const isMatched = await bcrypt.compare(userPassword, this.password);
  return isMatched;
};

module.exports = mongoose.model("User", UserSchema);
